FROM kong/kubernetes-ingress-controller:3.3.1


Copy ./kong/plugins/soap-xml-handling-lib /usr/local/share/lua/5.1/kong/plugins/soap-xml-handling-lib
COPY ./kong/plugins/soap-xml-response-handling /usr/local/share/lua/5.1/kong/plugins/soap-xml-response-handling
COPY ./kong/plugins/soap-xml-request-handling /usr/local/share/lua/5.1/kong/plugins/soap-xml-request-handling

COPY ./kong/saxon/so/amd64 /usr/local/lib/kongsaxon

ENV LD_LIBRARY_PATH=/usr/local/lib/kongsaxon
ENV KONG_PLUGINS=bundled,soap-xml-request-handling
