version: '3.8'

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass

  kong-migrations:
    image: kong-custom
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    command: ["kong", "migrations", "bootstrap"]
    restart: on-failure

  kong-gateway:
    image: kong-custom
    container_name: kong-gateway
    depends_on:
      - kong-database
    networks:
      - kong-net
    ports:
      - "8000:8000"   # Proxy HTTP port
      - "8443:8443"   # Proxy HTTPS port
      - "8001:8001"   # Admin API HTTP port
      - "8444:8444"   # Admin API HTTPS port
      - "8002:8002"   # Admin GUI HTTP port
      - "8445:8445"   # Admin GUI HTTPS port
      - "8003:8003"   # Custom port 1
      - "8004:8004"   # Custom port 2
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    restart: always


