[build-system]
requires = [
         "setuptools ~= 68.2.2",
         "cython ~= 0.29.36"
]
build-backend = "setuptools.build_meta"
[tool.cibuildwheel]
build = "*"
skip = ["cp36*", "cp37*", "pp*", "cp*musl*"]
archs = ["x86_64"]
environment.LD_LIBRARY_PATH = "/project/libs/nix"

